# Generated by Django 4.1 on 2023-03-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="uuid",
            new_name="id",
        ),
    ]
